Micronaut Views JStachio includes api:views.jstachio.JStachioViewsRenderer[] which uses
https://github.com/jstachio/jstachio[JStachio] A type-safe compiled Mustache based template engine.

Add the `micronaut-views-jstachio` dependency to your classpath.

dependency:micronaut-views-jstachio[groupId="io.micronaut.views"]

The example shown in the <<views, Views>> section, could be rendered with the following JStachio 
annotated model and template:

[source,java]
.src/main/java/myapp/HomeModel.java
----
//Normally you would put the JStacheConfig annotation on package-info or module-info
//but it can be placed on the model class directly
@JStacheConfig(using = MicronautJStacheConfig.class) 
@JStache(path = "home")
public record HomeModel(@Nullable String username, boolean loggedIn) {

}
----

[source,html]
.src/main/resources/views/home.mustache
----
include::{testsviewsJstachio}/resources/views/home.mustache[]
----

JStachio unlike most templating engines must have an annotated model class
that then references the template.

=== Compiling Templates

JStachio model and templates must be compiled. JStachio uses the Java annotation processor to do this.
The JStachio user guide covers how to set this up 
https://jstach.io/doc/jstachio/1.2.1/apidocs/#installation[Gradle or Maven].

=== Configuration

Because of the static nature of JStachio almost all configuration is done through annotations.
See the https://jstach.io/doc/jstachio/1.2.1/apidocs/#configuration[JStachio user guide] for more details.
Micronaut Views includes an opinionated static configuration of JStachio
api:views.jstachio.MicronautJStacheConfig[]. 
