Micronaut Views Jte includes api:views.jte.JteViewsRenderer[] which uses https://jte.gg[jte] (**J**ava **T**emplate **E**ngine), a
secure and lightweight template engine for Java and Kotlin.

Add the `micronaut-views-jte` dependency to your classpath.

dependency:micronaut-views-jte[groupId="io.micronaut.views"]

The example shown in the <<views, Views>> section, could be rendered with the following Jte template:

[source,html]
.src/main/resources/views/home.jte
----
include::{testsviewsJte}/resources/views/home.jte[]
----

=== Compiling Templates

Jte templates may be precompiled at build time. This can be done by a https://jte.gg/pre-compiling/#gradle[Gradle plugin] or https://jte.gg/pre-compiling/#maven[Maven plugin]. If not precompiled, the application will need a JDK so it can compile templates at runtime.

=== Dynamic Reloading

When `dynamic` is enabled (see below), jte will load templates from the project source directory, and will reload them after changes.

=== Configuration

The properties used can be customized by overriding the values of:

include::{includedir}configurationProperties/io.micronaut.views.jte.JteViewsRendererConfigurationProperties.adoc[]

== .kte (Kotlin) templates

To use `.kte` (Kotlin) templates include the dependency:.

dependency:jte-kotlin[groupId="gg.jte"]
