Micronaut Views Thymeleaf includes api:views.thymeleaf.ThymeleafViewsRenderer[] which uses
the https://www.thymeleaf.org[Thymeleaf] Java template engine.

Add the `micronaut-views-thymeleaf` dependency to your classpath.

dependency:micronaut-views-thymeleaf[groupId="io.micronaut.views"]

Thymeleaf integration instantiates a `ClassLoaderTemplateResolver`.

The properties used can be customized by overriding the values of:

include::{includedir}configurationProperties/io.micronaut.views.thymeleaf.ThymeleafViewsRendererConfigurationProperties.adoc[]

The example shown in the <<views, Views>> section, could be rendered with the following Thymeleaf template:

[source,html]
.src/main/resources/views/home.html
----
include::{testsviewsThymeleaf}/resources/views/home.html[]
----

and layout:

[source,html]
.src/main/resources/views/layoutFile.html
----
include::{testsviewsThymeleaf}/resources/views/layoutFile.html[]
----

Use Thymeleaf templates with Micronaut i18n messages. Internationalization messages will be resolved from Micronaut's
MessageSource automatically. For more information on the MessageSource, see the core documentation.

TIP: See the guide for https://guides.micronaut.io/latest/micronaut-views-thymeleaf.html[Server-side HTML with Thymeleaf] to learn more.
