The views project has integration with the Micronaut security project.

api:views.model.security.SecurityViewModelProcessor[] is enabled by default and injects the current username in the view.

NOTE: `SecurityViewModelProcessor` is typed to `Map<String, Object>`. If are models are POJOs you will need to implement your own security api:views.model.ViewModelProcessor[].

The following properties allow you to customize the injection:

include::{includedir}configurationProperties/io.micronaut.views.model.security.SecurityViewModelProcessorConfigurationProperties.adoc[]

In a controller, you can return a model without specifying in the model the authenticated user:

[source,java]
.src/main/java/myapp/BooksController.java
----
include::{testsSuite}/java/io/micronaut/views/model/security/BooksController.java[tags=class]
----

and still access the authenticated user in the view (for example a velocity template):

[source,html]
.src/main/resources/views/books.vm
----
include::{testsSuite}/resources/views/securitydecorator.vm[tag=html]
----

You can access information about the current user with the `security` map.

=== CSRF Token View Model Processor

If you use the https://micronaut-projects.github.io/micronaut-security/latest/guide/#csrf[Micronaut Security CSRF module], there is also a view model processor for a model of type `Map<String, Object>`.
If a CSRF Token can be resolved,  `CSRFViewModelProcessor` adds it to the model.

The following properties allow you to customize the injection:

include::{includedir}configurationProperties/io.micronaut.views.model.security.CsrfViewModelProcessorConfigurationProperties.adoc[]


