This section outlines the breaking changes done in major versions of Micronaut Views.

=== 3.0.0

* A Reactive Views renderer api:views.ReactiveViewsRenderer[] has been introduced. `Soy` implementation uses it. Other template engine implementation render to a `Writable`
by implementing `api:views.WritableViewsRenderer[]`. `ViewsRenderer` is now a interface class extended by both pi:views.ReactiveViewsRenderer[]` and api:views.WritableViewsRenderer[].

* api:views.model.ViewModelProcessor[] no longer assumes a `Map<String,Object>` model and must be typed to the exact type of the model you would like to process.

* api:views.model.ViewsRenderer[] are now typed. Moreover, provided `ViewsRenderer` don't specify `@Produces(MediaType.TEXT_HTML)` and responses content type respect the content type defined for the route.

* `ViewsRenderer::modelOf` method has been moved to `ViewUtils::modelOf`

* Constant `EXTENSION_SEPARATOR` has been moved from `ViewsRenderer` to `ViewUtils`

== 2.0.0

* The `micronaut-views` dependency is no longer published. Replace the dependency with the one specific to the view implementation being used.
* Deprecated classes, constructors, etc have been removed.
* ViewsFilterOrderProvider has been removed. The view filter now always runs on `ServerFilterPhase.RENDERING`.
* Maven Group ID changed to `io.micronaut.views`