This section outlines the breaking changes done in major versions of Micronaut Views.

=== 6.0.0

- Turbo integration has been moved to its own dependency. To use the Turbo integration, add the following
   dependency:
+
dependency:micronaut-views-turbo[groupId="io.micronaut.views"]
+
The annotation `@TurboView` has been renamed to ann:views.turbo.TurboStreamView[].

- The `ViewsModelDecorator` and `TurboStreamRenderer` now have generic types for their data and Request type, which breaks binary compatibility.

- The global `ViewsFilter` has been removed and replaced with individual `ResponseFilters`.

- The method `ThymeleafViewsRenderer.render(String, IContext, Writer)` deprecated previously has been removed.
It is replaced by `render(String, Set<String>, IContext, Writer)`

=== 4.0.0

* The Soy dependency has been upgraded to version _2022-10-26_, which includes breaking changes. Among others, `.` is no longer allowed before template names. To know the full changes, we suggest link:https://github.com/google/closure-templates/compare/release-2022-03-02%E2%80%A6release-2022-03-07[looking at the commits] since there exist no release notes.
* To reduce the size of applications where Http requests are not required, the core library has been detached from the micronaut http library and no longer declares it as an api dependency.
  This change has added another Generic type to ViewRenderer, and breaks binary compatibility.

=== 3.0.0

* api:views.model.ViewModelProcessor[] no longer assumes a `Map<String,Object>` model and must be typed to the exact type of the model you would like to process.

* api:views.ViewsRenderer[] are now typed. Moreover, provided `ViewsRenderer` don't specify `@Produces(MediaType.TEXT_HTML)` and responses content type respect the content type defined for the route.

* Method `ViewsRenderer::render(String, T)` was removed. Use `ViewsRenderer::render(String, T, HttpRequest)` instead.

* Decoration of view model is now handled by api:views.ViewsModelDecorator[] and its default implementation api:views.DefaultViewsModelDecorator[]

* Resolution of view name is now handled by api:views.ViewsResolver[] and its default implementation api:views.DefaultViewsResolver[]

* Resolution of api:views.ViewsRenderer[] used to render a view is now handled by api:views.ViewsRendererLocator[] and its default implementation api:views.DefaultViewsRendererLocator[]

* `ViewsRenderer::modelOf` method has been moved to `ViewUtils::modelOf`

* Constant `EXTENSION_SEPARATOR` has been moved from `ViewsRenderer` to `ViewUtils`

== 2.0.0

* The `micronaut-views` dependency is no longer published. Replace the dependency with the one specific to the view implementation being used.
* Deprecated classes, constructors, etc have been removed.
* ViewsFilterOrderProvider has been removed. The view filter now always runs on `ServerFilterPhase.RENDERING`.
* Maven Group ID changed to `io.micronaut.views`
