introduction: Introduction
releaseHistory: Release History
views:
  title: Server Side View Rendering
  templates:
    title: Template Engines
    thymeleaf: Thymeleaf
    handlebars: Handlebars.java
    velocity: Apache Velocity
    freemarker: Apache Freemarker
    rocker: Rocker
    soy:
      title: Soy/Closure Support
      soyconfiguration: Soy Configuration
      soyusage: Soy Usage
      soyfeaturestemplatesecurity: Soy Features - Template Security
      soyfeaturesremaining: Soy Features - Remaining
      buildingsoy: Building Soy
    pebble: Pebble
    jte: JTE
  model:
    title: Working with Models
    custom: Dynamically Enriching Models
  turbo:
    title: Turbo
    turboFrameView: TurboFrameView annotation
    turboFrameBuilder:  TurboFrame Builder
    turboStreamFluidApi: Turbo Stream Fluid API
    turboView: TurboView Annotation
    turboStreamContentType: Turbo Stream Media Type
    turboStreamTemplate: Turbo Streams with Templates
  security:
    title: Security
    csp: Content Security Policy
    security-model-enhancement: Integration with Micronaut Security
  graal: GraalVM Support
breaks: Breaking Changes
repository: Repository