introduction: Introduction
releaseHistory: Release History
views:
  title: Server Side View Rendering
  templates:
    title: Template Engines
    thymeleaf: Thymeleaf
    handlebars: Handlebars.java
    velocity: Apache Velocity
    freemarker: Apache Freemarker
    rocker: Rocker
    soy:
      title: Soy/Closure Support
      soyconfiguration: Soy Configuration
      soyusage: Soy Usage
      soyfeaturestemplatesecurity: Soy Features - Template Security
      soyfeaturesrenaming: Soy Features - Renaming
      buildingsoy: Building Soy
    pebble: Pebble
    jte: JTE
    jstachio:
      title: JStachio
      jstachioInstallation: JStachio Installation
      jstachioExample: JStachio Example
    react:
      title: React SSR
      reactpreparingjs: Preparing your Javascript
      reactsettingproperties: Setting serving properties
      reactprefetch: Prefetching API requests
      preact: Integrating with Preact
      reactrenderscripts: Render scripts
      reacttodo: Known limitations
  model:
    title: Working with Models
    custom: Dynamically Enriching Models
  fieldset:
    title: Fieldset Generation
    fieldsetExample: Form Generation Example
    fieldsetAnnotations: Fieldset Annotations
    fieldsetFetcher: Radio, Checkbox and Option Fetcher
    customFormElement: Custom Form Elements
  htmx:
    title: HTMX
    htmxRequestHeaders: HTMX Request Headers
    outOfBandSwaps: Out of Band Swaps
    htmxResponseHeaders: HTMX Response Headers
  turbo:
    title: Turbo
    turboFrameView: TurboFrameView annotation
    turboFrameBuilder:  TurboFrame Builder
    turboStreamFluidApi: Turbo Stream Fluid API
    turboView: TurboView Annotation
    turboStreamContentType: Turbo Stream Media Type
    turboStreamTemplate: Turbo Streams with Templates
    turboGuides: Guides
  security:
    title: Security
    csp: Content Security Policy
    security-model-enhancement: Integration with Micronaut Security
  graal: GraalVM Support
viewsGuides: Guides
breaks: Breaking Changes
repository: Repository
