plugins {
    id("io.micronaut.build.internal.views-base")
    id("io.micronaut.build.internal.module")
    id("org.sonatype.gradle.plugins.scan")
}

ossIndexAudit {
    excludeCoordinates = [
            "io.pebbletemplates:pebble:4.1.1" // CVE-2025-1686 is mitigated by disabling the Pebble {% include %} tag via DisallowExtensionCustomizerBuilder.
    ]
}
