[versions]
freemarker = "2.3.31"
handlebars = "4.3.0"
jte = "2.0.2"
pebble = "3.1.5"
rocker = "1.3.0"
snake-yaml = "1.30"
soy = "2022-03-02"
thymeleaf = "3.0.15.RELEASE"
thymeleaf-extra-java8time = "3.0.4.RELEASE"
velocity = "2.3"
kotlin = "1.6.20"
kotlinx-coroutines = "1.6.1"

# Micronaut
micronaut = "3.4.3"


[libraries]
# BOMs
boms-micronaut = { module = "io.micronaut:micronaut-bom", version.ref = "micronaut" }

# Micronaut
micronaut-graal = { module = "io.micronaut:micronaut-graal", version.ref = "micronaut" }
micronaut-http = { module = "io.micronaut:micronaut-http", version.ref = "micronaut" }
micronaut-http-client = { module = "io.micronaut:micronaut-http-client", version.ref = "micronaut" }
micronaut-http-server = { module = "io.micronaut:micronaut-http-server", version.ref = "micronaut" }
micronaut-http-server-netty = { module = "io.micronaut:micronaut-http-server-netty", version.ref = "micronaut" }
micronaut-inject = { module = "io.micronaut:micronaut-inject", version.ref = "micronaut" }
micronaut-inject-groovy = { module = "io.micronaut:micronaut-inject-groovy", version.ref = "micronaut" }
micronaut-inject-java = { module = "io.micronaut:micronaut-inject-java", version.ref = "micronaut" }
micronaut-management = { module = "io.micronaut:micronaut-management", version.ref = "micronaut" }
micronaut-runtime = { module = "io.micronaut:micronaut-runtime", version.ref = "micronaut" }
micronaut-security = { module = "io.micronaut.security:micronaut-security" }
micronaut-test-junit5 = { module = "io.micronaut.test:micronaut-test-junit5" }
micronaut-test-spock = { module = "io.micronaut.test:micronaut-test-spock" }
micronaut-validation = { module = "io.micronaut:micronaut-validation", version.ref = "micronaut" }

freemarker = { module = "org.freemarker:freemarker", version.ref = "freemarker" }
handlebars = { module = "com.github.jknack:handlebars", version.ref = "handlebars" }
jte = { module = "gg.jte:jte", version.ref = "jte" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
logback-classic = { module = "ch.qos.logback:logback-classic" }
pebble = { module = "io.pebbletemplates:pebble", version.ref = "pebble" }
reactor-core = { module = "io.projectreactor:reactor-core" }
rocker-runtime = { module = "com.fizzed:rocker-runtime", version.ref = "rocker" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snake-yaml" }
soy = { module = "com.google.template:soy", version.ref = "soy" }
thymeleaf = { module = "org.thymeleaf:thymeleaf", version.ref = "thymeleaf" }
thymeleaf-extras-java8time = { module = "org.thymeleaf.extras:thymeleaf-extras-java8time", version.ref = "thymeleaf-extra-java8time" }
velocity-engine-core = { module = "org.apache.velocity:velocity-engine-core", version.ref = "velocity" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
