Soy has powerful built-in renaming features, that both obfuscate and optimize your code as it is rendered. Renaming is
opt-in and requires a few things:

* A compatible CSS compiler (https://github.com/google/closure-stylesheets[GSS / Closure Stylesheets] is a good one)
* Special calls in your templates that map CSS classes and IDs
* JSON renaming map provided at compile time for JS templates, and runtime for Java rendering

Renaming is similar to other frameworks' corresponding uglify features, but it's significantly more powerful, allowing
you to rewrite CSS classes and IDs as you would JavaScript symbols. Here's how you can use renaming server-side with
Micronaut Views Soy:

1. Configure Micronaut Views Soy to enable renaming:

[configuration]
----
micronaut:
  views:
    soy:
      enabled: true
      renaming: true
----

2. When building your styles with GSS, or a similar tool, generate a rewrite map:
[source,bash]
> java -jar closure-stylesheets.jar \
    --output-renaming-map-format JSON \
    --output-renaming-map src/main/resources/renaming-map.json \
    --rename CLOSURE \
    [...inputs...] > src/main/resources/styles/app-styles.min.css

3. In your template sources, annotate CSS classes with `{css('name')}` calls. Note that the value passed into each call
must be a string literal (variables cannot be used):
[source,soy]
{template .foo}
  <div class="{css('my-cool-class')} {css('my-cool-class-active')}">
    ... content, and stuff...
  </div>
{/template}

4. In your CSS, use the names you mentioned in your template:
[source,css]
.my-cool-class {
  color: blue;
}
.my-cool-class-active {
  background: yellow;
}

5. Compile your templates (see: _Building Soy_).
[source,bash]
> java -jar SoyToJbcSrcCompiler.jar \
    --output templates.jar \
    --srcs [...templates...];

The last step is to provide the renaming map to Micronaut Views Soy:

snippet::io.micronaut.docs.soy.RewriteMapProvider[tags="clazz"]

Then, your output will be renamed. Referencing the Soy template sample above, output would look something like this:
```html
<div class="a-b-c a-b-c-d">... content, and stuff...</div>
```

With your CSS rewritten and minified to match:
```css
.a-b-c{color:blue;}.a-b-c-d{background:yellow;}
```
