IMPORTANT: With Micronaut JStachio, you cannot use the api:views.View[] annotation,
respond in your controller a api:views.ModelAndView[] or use
https://micronaut-projects.github.io/micronaut-views/latest/guide/configurationreference.html#io.micronaut.views.ViewsConfigurationProperties[Micronaut Views Configuration]
to configure the views directory since it does not use the api:views.ViewsFilter[].

Instead, a controller returns a model annotated with `@JStache` referencing the `view` name.

NOTE: JStachio generates the template renderers with a Java annotation processor from `@JStache` annotated Java classes and records, so the examples in this section are Java only.

snippet::io.micronaut.views.jstachio.pkginfo.HomeController[tags="clazz",project="views-jstachio",language="java",title="HomeController.java"]

snippet::io.micronaut.views.jstachio.pkginfo.HomeModel[project="views-jstachio",language="java",title="HomeModel.java"]

You can provide a `suffix` and `prefix` for every model with the `@JStacheConfig` annotation.

Add a `package-info.java` in the same package of your model classes.

snippet::io.micronaut.views.jstachio.pkginfo.package-info[project="views-jstachio",language="java",title="package-info.java"]

The previous example renders the following template:

[source,html]
.src/main/resources/views/home.mustache
----
include::{testsviewsJstachio}/resources/views/home.mustache[]
----

