An app that uses SSR needs the React components to be bundled twice, once for the client and once for the server. For the server you need to make a Javascript module bundle that imports and then re-exports the (page) components you will render, along with `React`, `ReactServerDOM` and if you wish to benefit from the server-side request prefetching, `SWRConfig` from the `swr` module. The bundle must be compatible with GraalJS, which is not NodeJS and thus doesn't support the same set of APIs. You will also need to create a client-side bundle as per usual, and change how you start up React.

TIP: This tutorial doesn't take you through how to create a ReactJS project from scratch - please refer to the React documentation for that.

To start we will need a `server.js` file. It should be a part of your frontend project and can be named and placed wherever you like, as the server will only need the final compiled bundle. Your `server.js` should look like this:

[source,javascript]
.src/main/js/server.js
----
include::{srcjsReact}/server.js[]
----

Add your page components as imports, and then also to the export line. We will now set up Webpack to turn this file into a bundle.

1. Run `npm i webpack node-polyfill-webpack-plugin text-encoding` to install some extra packages that are needed.
2. Create a config file called e.g. `webpack.server.js` like the following:

[source,javascript]
.src/main/js/webpack.server.js
----
include::{srcjsReact}/webpack.server.js[]
----

This Webpack config does several things:

* It polyfills APIs that lack a native implementation in the GraalJS engine.
* It ensures the output is a native Javascript module.
* It names the result `ssr-components.mjs` which is the only name Micronaut React SSR accepts. All components must be in one server side bundle currently.
* It makes the `SERVER` variable be statically true when the Javascript is being bundled for server-side rendering. This allows you to include/exclude code blocks at bundle optimization time.

You can use such a config by running `npx webpack --mode production --config webpack.server.js`. Add the `--watch` flag if you want the bundle to be recreated whenever an input file changes. Micronaut React SSR will notice if the bundle file has changed on disk and reload it.

Now create `client.js`. This will contain the Javascript that runs once the page is loaded, and which will "hydrate" the React app (reconnect the event handlers to the pre-existing DOM). It should look like this:

[source,javascript]
.src/main/js/client.js
----
include::{srcjsReact}/client.js[]
----

Depending on how you configure minification, you may also need to import your page components here. This small snippet of code reads the `__micronaut_boot` object which is generated by the Micronaut React SSR renderer just before your `client.js` code is loaded. It contains the component named in your `@View("MyPageComponent")` annotation, which is then loaded assuming it is in a Javascript module of the same name. The props that will be passed to that page component as generated from the object you return from your controller method. If you wish you can wrap `<PageComponent/>` here with any contexts you need.

And now for the `webpack.client.js` config:

[source,javascript]
.src/main/js/webpack.client.js
----
include::{srcjsReact}/webpack.client.js[]
----

It tells Webpack to generate a series of JS files that are then placed in the `src/main/resources/static` directory.

Run Webpack to generate the needed Javascript files for both client and server.
