Micronaut includes api:views.soy.SoySauceViewsRenderer[] which uses
https://github.com/google/closure-templates[Soy, also known as Closure Templates], a template
compiler from Google. Soy is usable standalone, or together with the rest of the
https://developers.google.com/closure[Closure Tools ecosystem], and targets both server-side and
client-side, with the ability to compile templates into Java, Python, or JavaScript.


In addition to the <<views, Views>> dependency, add the following dependency.

dependency:soy[groupId="com.google.template",scope="compile",version="2019-09-03"]

The example shown in the <<views, Views>> section, could be rendered with the following Soy template:

[source,soy]
.src/main/resources/home.soy
----
include::{testsviewsSoy}/resources/home.soy[]
----

=== Usage

Soy integration is invoked by providing a bean that complies with `SoyFileSetProvider`. The object that complies with
this interface is responsible for loading the Soy templates, either in compiled or source form.

Both server-side Soy rendering layers are supported in Micronaut:

* `SoySauceViewsRenderer`: This renderer uses templates pre-compiled to Java bytecode, generally AOT, with
  `SoyToJbcSrcCompiler`. If compiled templates can't be located by the `SoyFileSetProvider`, templates are pre-compiled
  into bytecode at server startup. This can be impactful on startup-time, so, if that's an important metric for your
  app, pre-compile your templates using the AOT bytecode compiler.

Which renderer is active depends on the Micronaut configuration:

[source,yaml]
micronaut:
  views:
    soy:
      enabled: true

After wiring up your `SoyFileSetProvider`, and configuring Micronaut, you can render templates like so:

[source,java]
@Validated
@Controller("/")
public class HelloWorld {
  @Get(value = "/soy", produces = MediaType.TEXT_HTML)
  @View("some.soy.template.path")
  public HttpResponse soyDemo() {
    // return template context
    return HttpResponse.ok(ImmutableMap.of("username", "jdoe", "loggedIn", true));
  }
}

The return value is converted to Soy template context parameters, and passed to the `@View`-annotation-bound template.


=== Configuration

The entire set of supported Soy configuration properties are documented below:

|=======
|Configuration property |Type |Default value
|`micronaut.views.soy.enabled` |`Boolean` |`false`
|`micronaut.views.soy.renaming` |`Boolean` |`false`
|=======


=== Features: Template Security

Soy/Closure Templates has seen significant work from Google where security is concerned, both in the browser and on the
backend. Soy is extremely strict and strongly typed, with validation being performed by Soy and then subsequently either
by `javac` or Closure Compiler, and additionally in some cases at render-time. What follows is a brief guide of these
security features. These are outlined in more detail over in the
https://github.com/google/closure-templates/blob/master/documentation/reference/security.md[Closure Templates docs].

==== Front-end Security

* _Trusted URIs:_ Soy is smart enough to know that `scriptUrl` might be influenced by user input, and, therefore,
  introduces an https://www.owasp.org/index.php/Cross-site_Scripting_(XSS)[XSS vulnerability] when used as a script
  `src`. To inject resources, use `uri`:
[source,soy]
/* I won't compile because I introduce a vulnerability */
{template .foo}
  {@param scriptUrl: string}
  <script src={$scriptUrl}></script>
{/template}

    /* I will compile because I accept a URI type, which is trusted in this context */
    {template .foo}
      {@param scriptUrl: uri}
      <script src={$scriptUrl}></script>
    {/template}

* _Markup:_ Passing in HTML for `content` won't work if it's a `string`. Soy will comply and inject your content, but it
  will be escaped. To inject markup, use the strict markup types (`js`, `css`, `html`).
[source,soy]
/* I will compile, but I may escape the injected content if it contains markup. */
{template .foo}
  {@param content: string}
  <b>{$content}</b>
{/template}

    /* I allow markup because the appropriate types are used */
    {template .foo}
      {@param content: html}
      <b>{$content}</b>
    {/template}

==== Back-end Security

* _CSP Nonce Support_: Soy has support for _Content Security Policy_ (https://www.w3.org/TR/CSP3/[Level 3]),
  specifically, embedding server-generated `nonce` attributes in `<script>` tags. This is accomplished by providing an
  https://github.com/google/closure-templates/blob/b0b39f9af2fed78333ddb7963266e9d2db3df094/documentation/dev/security.md#content-security-policy-csp-content_security_policy["injected value"]
  with the key `"csp_nonce"`. The nonce, which
  https://csp.withgoogle.com/docs/faq.html#generating-nonces[should change on each page load], is available in the
  template like so:
[source,soy]
/* Soy will inject the nonce for you, but if you need it anyway, this is how you access it. */
{template .foo}
  {@param injectedScript: uri}
  {@inject csp_nonce: string}
  <script src={$injectedScript} nonce={$csp_nonce} type="text/javascript"></script>
{/template}


=== Features: Renaming

Soy has powerful built-in renaming features, that both obfuscate and optimize your code as it is rendered. Renaming is
opt-in and requires a few things:

* A compatible CSS compiler (https://github.com/google/closure-stylesheets[GSS / Closure Stylesheets] is a good one)
* Special calls in your templates that map CSS classes and IDs
* JSON renaming map provided at compile time for JS templates, and runtime for Java rendering

Renaming is similar to other frameworks' correponding uglify features, but it's significantly more powerful, allowing
you to rewrite CSS classes and IDs as you would JavaScript symbols. Here's how you can use renaming server-side with
Micronaut:

1. Configure Micronaut to enable renaming:
[source,yaml]
micronaut:
  views:
    soy:
      enabled: true
      renaming: true

2. When building your styles with GSS, or a similar tool, generate a rewrite map:
[source,bash]
> java -jar closure-stylesheets.jar \
    --output-renaming-map-format JSON \
    --output-renaming-map src/main/resources/renaming-map.json \
    --rename CLOSURE \
    [...inputs...] > src/main/resources/styles/app-styles.min.css

3. In your template sources, annotate CSS classes with `{css('name')}` calls. Note that the value passed into each call
   must be a string literal (variables cannot be used):
[source,soy]
{template .foo}
  <div class="{css('my-cool-class')} {css('my-cool-class-active')}">
    ... content, and stuff...
  </div>
{/template}

4. In your CSS, use the names you mentioned in your template:
[source,css]
.my-cool-class {
  color: blue;
}
.my-cool-class-active {
  background: yellow;
}

5. Compile your templates (see: _Building Soy_).
[source,bash]
> java -jar SoyToJbcSrcCompiler.jar \
    --output templates.jar \
    --srcs [...templates...];

The last step is to provide the renaming map to Micronaut:
```java
@Singleton
public class RewriteMapProvider implements SoyNamingMapProvider {
  /** Filename for the JSON class renaming map. */
  private static final String RENAMING_MAP_NAME = "renaming-map.json";

  /** Naming map to use for classes. */
  private static SoyCssRenamingMap CSS_RENAMING_MAP = null;

  /**
   * Load JSON embedded in a JAR resource into a naming map for Soy rendering.
   *
   * @param mapPath URL to the JAR resource we should load.
   */
  @Nullable
  private static Map<String, String> loadMapFromJSON(URL mapPath) {
    try {
      return new ObjectMapper().readValue(mapPath, new TypeReference<Map<String, String>>() { });
    } catch (Throwable thr) {
      //handle `JsonMappingException` and `IOException`, if, for instance, you're using Jackson
      throw new RuntimeException(thr);
    }
  }

  static {
    final URL mapPath =
        SoyRenderConfigProvider.class.getClassLoader().getResource(RENAMING_MAP_NAME);
    if (mapPath != null) {
      // load the renaming map
      final Map<String, String> cssRenamingMap = loadMapFromJSON(mapPath);
      if (renamingMapRaw != null) {
        CSS_RENAMING_MAP = new SoyCssRenamingMap() {
          @Nullable @Override
          public String get(@NotNull String className) {
            // (or whatever logic you need to rewrite the class)
            return cssRenamingMap.get(className);
          }
        };
      }
    }
  }

  /**
   * Provide a CSS renaming map to Soy/Micronaut.
   *
   * @return Inflated Soy CSS renaming map.
   */
  @Nullable @Override public SoyCssRenamingMap cssRenamingMap() {
    return CSS_RENAMING_MAP;
  }
}
```

Then, your output will be renamed. Referencing the Soy template sample above, output would look something like this:
```html
<div class="a-b-c a-b-c-d">... content, and stuff...</div>
```

With your CSS rewritten and minified to match:
```css
.a-b-c{color:blue;}.a-b-c-d{background:yellow;}
```

=== Building Soy

Soy has tooling support from https://github.com/Medium/soynode[Node] (https://www.npmjs.com/package/gulp-soynode[Gulp],
https://www.npmjs.com/package/grunt-closure-soy[Grunt]),
http://mvnrepository.com/artifact/com.google.template/soy[Maven],
https://plugins.gradle.org/plugin/com.liferay.soy[Gradle], and
https://github.com/bazelbuild/rules_closure/#closure_js_template_library[Bazel]. You can also invoke each
Soy compiler directly via the runner classes for each one:

* https://github.com/google/closure-templates/blob/master/java/src/com/google/template/soy/SoyHeaderCompiler.java[SoyHeaderCompiler]:
Compile templates into light "headers," that can be used downstream as dependencies for other templates.
* https://github.com/google/closure-templates/blob/master/java/src/com/google/template/soy/SoyMsgExtractor.java[SoyMsgExtractor]:
Enables easy i18n by extracting `{msg desc=""}{/msg}` declarations for processing or translation.
* https://github.com/google/closure-templates/blob/master/java/src/com/google/template/soy/SoyParseInfoGenerator.java[SoyParseInfoGenerator]:
Generates template parser metadata information as Java sources.
* https://github.com/google/closure-templates/blob/master/java/src/com/google/template/soy/SoyPluginValidator.java[SoyPluginValidator]:
Validates `SoySourceFunction` definitions found in a set of JARs.
* https://github.com/google/closure-templates/blob/master/java/src/com/google/template/soy/SoyToIncrementalDomSrcCompiler.java[SoyToIncrementalDomSrcCompiler]:
Generate client-side templates that render with http://google.github.io/incremental-dom[IncrementalDOM] (AKA `idom`).
This compiler uses direct calls into the DOM to incrementally render content, as opposed to the traditional client-side
approach, which renders strings into `element.innerHTML`. This support is currently experimental and involves a number
of external dependencies.
* https://github.com/google/closure-templates/blob/master/java/src/com/google/template/soy/SoyToJbcSrcCompiler.java[SoyToJbcSrcCompiler]:
Compiles Soy templates directly to Java bytecode, packaged up in a JAR. These templates can be used together with
  https://search.maven.org/search?q=g:com.google.template%20AND%20a:soy&core=gav[Soy Java] for highly performant
server-side rendering.
* https://github.com/google/closure-templates/blob/master/java/src/com/google/template/soy/SoyToJsSrcCompiler.java[SoyToJsSrcCompiler]:
Traditional JS client-side compiler, which assembles strings of rendered template content. Like `idom`, these compiled
templates work well with Closure Compiler, and Closure Library via
  https://github.com/google/closure-library/tree/master/closure/goog/soy[`goog.soy`].
* https://github.com/google/closure-templates/blob/master/java/src/com/google/template/soy/SoyToPySrcCompiler.java[SoyToPySrcCompiler]:
Compiles templates into Python sources for use server-side.
