Micronaut includes api:views.thymeleaf.ThymeleafViewsRenderer[] which uses
the https://www.thymeleaf.org[Thymeleaf] Java template engine.

In addition to the <<views, Views>> dependency, add the following dependency on your classpath.

dependency:thymeleaf[groupId="org.thymeleaf",scope="runtime",version="3.0.11.RELEASE"]

Thymeleaf integration instantiates a `ClassLoaderTemplateResolver`.

The properties used can be customized by overriding the values of:

include::{includedir}configurationProperties/io.micronaut.views.thymeleaf.ThymeleafViewsRendererConfigurationProperties.adoc[]

The example shown in the <<views, Views>> section, could be rendered with the following Thymeleaf template:

[source,html]
.src/main/resources/views/home.html
----
include::{testsviewsThymeleaf}/resources/views/home.html[]
----

and layout:

[source,html]
.src/main/resources/views/layoutFile.html
----
include::{testsviewsThymeleaf}/resources/views/layoutFile.html[]
----

### Externalized Text

Use Thymeleaf templates with Micronaut i18n messages.  Micronaut includes api:views.thymeleaf.MicronautThymeMessageResolver[] to be used
in https://www.thymeleaf.org/apidocs/thymeleaf/3.0.11.RELEASE/org/thymeleaf/TemplateEngine.html[TemplateEngine].

Create a message source to access i18n messages, for example a file called `sample.properties`. Do this by creating a bean below:

[source,java]
.src/main/java/myapp/SampleMessageSource.java
----
include::{testsviewsThymeleaf}/java/io/micronaut/views/thymeleaf/SampleMessageSource.java[]
----

The message source will be integrated into the Thymeleaf `TemplateEngine` by Micronaut.

Define a properties file.

[source,properties]
.src/main/resources/i18n/sample.properties
----
include::{testsviewsThymeleaf}/resources/i18n/sample.properties[]
----

Then define an html template file.

[source,html]
.src/main/resources/views/thymeleaf/sample.html
----
include::{testsviewsThymeleaf}/resources/views/thymeleaf/sample.html[]
----

Use the `TemplateEngine` API below to resolve the template with Micronaut messages.

[source,java]
.snippet
----
include::{testsviewsThymeleaf}/groovy/io/micronaut/views/thymeleaf/MicronautThymeMessageResolverSpec.groovy[tags=imports]

...

include::{testsviewsThymeleaf}/groovy/io/micronaut/views/thymeleaf/MicronautThymeMessageResolverSpec.groovy[tags=bean]
include::{testsviewsThymeleaf}/groovy/io/micronaut/views/thymeleaf/MicronautThymeMessageResolverSpec.groovy[tags=process]

...
----