Imagine, you want to create an application which displays a form such as:

[source, html]
----
<form action="/books/save" method="post">
    <div class="mb-3">
        <label for="title" class="form-label">Title</label>
        <input type="text" name="title" value="" id="title" minlength="2" maxlength="255" class="form-control" required="required"/>
    </div>
    <div class="mb-3">
        <label for="pages" class="form-label">Pages</label>
        <input type="number" name="pages" value="" id="pages" min="1" max="21450" class="form-control" required="required"/>
    </div>
    <input type="submit" value="Submit" class="btn btn-primary"/>
</form>
----

You will create a representation for the form submission. Something like:

snippet::io.micronaut.views.docs.fieldset.BookSave[]

NOTE: The field types and the validation annotations in the previous code sample influence the form generation.

Then using the form generation API, create a controller such as:

snippet::io.micronaut.views.docs.fieldset.BookController[tags="clazz"]

https://micronaut.io/launch?features=views-thymeleaf[Micronaut Launch] or the Micronaut Command Line Interface (CLI) will generate Thymeleaf fragments to render a form when you select the `views-thymeleaf` feature.

Thanks to those fragments, rendering the form for the `/books/create` route in the previous example is really simple:

[source,html]
.src/main/resources/views/books/create.html
----
include::{testssuitefieldsetthymeleaf}/resources/views/books/create.html[]
----
