The ann:views.fields.annotations.InputCheckbox[], ann:views.fields.annotations.InputRadio[], and ann:views.fields.annotations.Select[] annotations allow you to specify a fetcher class to load data necessary for the form.

Imagine you want a form to associate an author with a book form, such as:

[source, html]
----
<form action="/books/authors/save" method="post">
    <input type="hidden" name="bookId" value="1"/>
    <div class="mb-3">
        <label for="authorId" class="form-label">Author Id</label>
        <select name="authorId" id="authorId" class="form-select" required="required">
            <option value="1">Kishori Sharan</option>
            <option value="2">Peter Späth</option>
            <option value="3">Sam Newman</option>
        </select>
    </div>
    <input type="submit" value="Submit" class="btn btn-primary"/>
</form>"
----

You will create a representation for the form submission. Something like:

snippet::io.micronaut.views.docs.fieldset.BookAuthorSave[tags="clazz",languages="java,kotlin,groovy"]

The `fetcher` member of the `Select` annotation allows you to specify a class. `AuthorFetcher` is a `Singleton` of type `OptionFetcher`, and you could write it, for example, like this:

snippet::io.micronaut.views.docs.fieldset.AuthorFetcher[tags="clazz",languages="java,kotlin,groovy"]

[.lang-python]
--
NOTE: A Python class cannot currently implement api:views.fields.fetchers.OptionFetcher[]: its `generate(Class<T>)` and `generate(T)` methods are overloads with the same number of parameters, and Python has no method overloading. Option fetchers must be written in Java, Kotlin or Groovy.
--
